version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: smart_learning
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/smart_learning
      - JWT_SECRET=devsecret
    depends_on:
      - mongo

volumes:
  mongo_data:
